### ISSUE TITLE
Distance Computation

### ISSUE THREAD

**Issue by HughP** [patorjk/keyboard-layout-analyzer#1]
@patorjk I was looking at your code to try and see how you were computing distance for the distance one's fingers travel when they type a text. You display distance when you provide analysis results in your Keyboard Layout Analysis javascript app like here: http://patorjk.com/keyboard-layout-analyzer/#/results

I found some [distance computation here](https://github.com/patorjk/keyboard-layout-analyzer/blob/e668ee50132342ee9e73e8d40309907694349454/js/analyzer.js)

``` javascript
function distanceBetweenKeys(keyMap, keyIndex1, keyIndex2) {
        var xDiff = keyMap[keyIndex1].cx - keyMap[keyIndex2].cx,
            yDiff = keyMap[keyIndex1].cy - keyMap[keyIndex2].cy;
        return Math.sqrt(xDiff*xDiff + yDiff*yDiff);
```

However, it seems to me that real numbers are needed somehow. Where are the real numbers? do you have an x,y coordinate table somewhere?

I looked in the layouts folder at a layout and it does not seem to have an x,y coordinate in the syntax. Can you point me to what I am missing?

**Comment by HughP** [comment]
BTW: I found your blog post about 19mm between the center points: http://patorjk.com/blog/2009/07/12/typing-distance/ It seems that the technical term here for this distance is pitch. The reference you link to is no-longer available from the source but it is in the Internet archive here: http://web.archive.org/web/20090630115240/http://www.technewsworld.com/story/67444.html

There are some other references out there for pitch, which can vary depending on the manufacturer including the following:
- http://www.ergonomicsmadeeasy.com/pages/keypitch
- http://www.emperorlinux.com/systemmatrix/keyboards/

**Comment by patorjk** [comment]
Good catch! They're in the files in the /common/pat/keyboard/js/ directory, which I forgot to include in this repo. I'll do some updates in an hour or two to fix this.

**Comment by patorjk** [comment]
Updated the source to add in the files under the common directory. You'll find the key maps in this file:

https://github.com/patorjk/keyboard-layout-analyzer/blob/master/common/pat/keyboard/js/kb.js#L807

Each key map has a property called "pixelsPerCm" that's used for calculating the distance.

**Comment by HughP** [comment]
@patorjk Thank you very much.
