### ISSUE TITLE
Is this a typo?

### ISSUE THREAD

**Issue by iandoug** [patorjk/keyboard-layout-analyzer#8]
Hi

in main.js and analyzer.js you have
KLA.results.fingerScores[ii] = total / 260; // 220 is max possible score
results.fingerScores[ii] = total / 260; // 220 is max possible score

Is there a typo there or are both 260 and 220 correct?

On a related note, if for example I get a final score of 70, does that mean the layout is 70% of optimal?

thanks, Ian

**Comment by patorjk** [comment]
After taking a look, it looks like the code is correct (the max score possible is 260), and the comment is incorrect. I imagine I updated the code without changing the comment. This section is a little confusing and definitely needs a better comments. Thank you for the heads up.
